export const salesColumns = [
  {
    field: "paid_rest_usd",
    headerName: "المدفوع/الباقي USD ",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
    border: 1,
  },
  {
    field: "paid_rest_lira",
    headerName: "المدفوع/الباقي L.L",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "discount",
    headerName: "حسم",
    type: "string",
    width: 80,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "total_price",
    headerName: "الاجمالي",
    type: "string",
    width: 60,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "single_price",
    headerName: "الفردي",
    type: "string",
    width: 60,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "creditor",
    headerName: "دائن",
    type: "string",
    width: 60,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "agent",
    headerName: "العميل",
    type: "string",
    width: 60,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "quantity",
    headerName: "الكميه",
    type: "number",
    width: 60,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "category",
    headerName: "اسم الصنف",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "product_name",
    headerName: "اسم المنتج",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "product_id",
    headerName: "رقم المنتج",
    type: "number",
    width: 80,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "user_name",
    headerName: "اسم المسخدم",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "time",
    headerName: "الوقت",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "id",
    headerName: "ID",
    width: 15,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
];

export const creditorColumns = [
  {
    field: "paid_rest_usd",
    headerName: "المدفوع/الباقي USD ",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
    border: 1,
  },
  {
    field: "paid_rest_lira",
    headerName: "المدفوع/الباقي L.L",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "discount",
    headerName: "حسم",
    type: "string",
    width: 80,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "user_name",
    headerName: "اسم المسخدم",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "time",
    headerName: "الوقت",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "id",
    headerName: "ID",
    width: 15,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
];

export const expensesColumns = [
  {
    field: "paid_rest_usd",
    headerName: "المدفوع/الباقي USD ",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
    border: 1,
  },
  {
    field: "paid_rest_lira",
    headerName: "المدفوع/الباقي L.L",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "description",
    headerName: "وصف",
    type: "string",
    width: 125,
    editable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "user_name",
    headerName: "اسم المسخدم",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "time",
    headerName: "الوقت",
    type: "string",
    width: 80,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "id",
    headerName: "ID",
    width: 15,
    editable: false,
    align: "center",
    headerAlign: "center",
  },
];

export const rows = [
  {
    id: 1,
    paid_rest_usd: "15$",
    paid_rest_lira: "115,000 L.L",
    total_price: "45$",
    discount: "1$",
    single_price: 1,
    creditor: "لا",
    agent: "علي",
    description: "ubs1",
    quantity: 5,
    category: "هواتف",
    product_name: "شاحن",
    product_id: 1567,
    user_name: "ali",
    time: "12:35",
  },
  {
    id: 1,
    paid_rest_usd: "15$",
    paid_rest_lira: "115,000 L.L",
    total_price: "45$",
    discount: "1$",
    single_price: 1,
    creditor: "لا",
    agent: "علي",
    description: "ubs1",
    quantity: 5,
    category: "هواتف",
    product_name: "شاحن",
    product_id: 1567,
    user_name: "ali",
    time: "12:35",
  },
  {
    id: 1,
    paid_rest_usd: "15$",
    paid_rest_lira: "115,000 L.L",
    total_price: "45$",
    discount: "1$",
    single_price: 1,
    creditor: "لا",
    agent: "علي",
    description: "ubs1",
    quantity: 5,
    category: "هواتف",
    product_name: "شاحن",
    product_id: 1567,
    user_name: "ali",
    time: "12:35",
  },
  {
    id: 1,
    paid_rest_usd: "15$",
    paid_rest_lira: "115,000 L.L",
    total_price: "45$",
    discount: "1$",
    single_price: 1,
    creditor: "لا",
    agent: "علي",
    description: "ubs1",
    quantity: 5,
    category: "هواتف",
    product_name: "شاحن",
    product_id: 1567,
    user_name: "ali",
    time: "12:35",
  },
  {
    id: 1,
    paid_rest_usd: "15$",
    paid_rest_lira: "115,000 L.L",
    total_price: "45$",
    discount: "1$",
    single_price: 1,
    creditor: "لا",
    agent: "علي",
    description: "ubs1",
    quantity: 5,
    category: "هواتف",
    product_name: "شاحن",
    product_id: 1567,
    user_name: "ali",
    time: "12:35",
  },
  {
    id: 1,
    paid_rest_usd: "15$",
    paid_rest_lira: "115,000 L.L",
    total_price: "45$",
    discount: "1$",
    single_price: 1,
    creditor: "لا",
    agent: "علي",
    description: "ubs1",
    quantity: 5,
    category: "هواتف",
    product_name: "شاحن",
    product_id: 1567,
    user_name: "ali",
    time: "12:35",
  },
];